# FROM python:3.12.4-slim
# WORKDIR /app
# COPY requirements.txt requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt
# COPY . .
# EXPOSE 8501
# CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]


FROM python:3.12.4-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8501
CMD ["watchfiles", "streamlit run app.py --server.port=8501 --server.address=0.0.0.0"]
